databases:
  - name: booksmart-database
    databaseName: booksmart
    user: booksmart_user

services:
  - type: web
    name: booksmart
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: booksmart-database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
