@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2LCJleHAiOjE2NDY1MTY1NjB9.H0BZhnnBdZUr_hv535B7r34vAZkmcNHZ_cYbPRqMI88
#Christina (user_id: 6)

### Clubs Index
GET http://localhost:3000/clubs

###
#Books Index - Search Titles for Work Ids
GET http://localhost:3000/books
Content-Type: application/json

{
  "title_search": "east of eden"
}

### Clubs Create
#Note: ISBN comes through params after user runs Book Index on frontend

POST http://localhost:3000/clubs
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "isbn": "9780142004234",
  "name": "East V West"
}

### Clubs Show

GET http://localhost:3000/clubs/17

### Clubs Update

PATCH http://localhost:3000/clubs/17
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "name": "Riding the Second Wave",
  "is_active": true
}

###