@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2LCJleHAiOjE2NDY3ODg4MjJ9.ld_J2bamG2FoCRlO0Dx_Gzk3wQkMwAvd5kUOkeVwNcY
#Christina (user_id: 6)

### Clubs Index
GET http://localhost:3000/clubs

###
#Books Index - Search Titles for Work Ids
GET http://localhost:3000/books
Content-Type: application/json

{
  "title_search": "the woman who"
}

### Clubs Create
#Note: ISBN comes through params after user runs Book Index on frontend

POST http://localhost:3000/clubs
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "isbn": "9780767930512",
  "name": "Feminist Book Club"
}

### Clubs Show

GET http://localhost:3000/clubs/5
Content-Type: application/json
Authorization: Bearer {{ jwt }}

### Clubs Update

PATCH http://localhost:3000/clubs/5
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "is_active": true
}

###