@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2LCJleHAiOjE2NDY1MTY1NjB9.H0BZhnnBdZUr_hv535B7r34vAZkmcNHZ_cYbPRqMI88
#Christina (user_id: 6)

### Messages Create
POST http://localhost:3000/messages/
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "club_id": 19,
  "body": "Question 2: This is a quintessentially American book because...",
  "category": "formal"
}

### Messages Update
PATCH http://localhost:3000/messages/31
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "body": "Question 2: This is a quintessentially American book because of the way that Steinbeck uses...",
  "category": "informal"
}

### Messages Destroy

DELETE http://localhost:3000/messages/28
Content-Type: application/json
Authorization: Bearer {{ jwt }}