@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMSwiZXhwIjoxNjQ2MzI1NjQxfQ.4J9HK21ISRnr9MNdONJpT8KxdBdfrzv57154F86VdBc
#Corrie signed in (11)

### Membership Create
POST http://localhost:3000/memberships/
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "club_id": 7
}

### Membership Destroy

DELETE http://localhost:3000/memberships/25
Content-Type: application/json
Authorization: Bearer {{ jwt }}