@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxNCwiZXhwIjoxNjQ2NjgyMDMzfQ.1Bbpo06N4OmqhZmQLzjjTzmil0PGTjFXE7abMiaGnks
#Betty (user_id: 14)

### Messages Create
POST http://localhost:3000/messages/
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "club_id": 5,
  "body": "I'm the best ever",
  "category": "informal"
}

### Messages Update
PATCH http://localhost:3000/messages/32
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "body": "You're the best"
}

### Messages Destroy

DELETE http://localhost:3000/messages/32
Content-Type: application/json
Authorization: Bearer {{ jwt }}