@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDcwOTU5Mzl9.vqlpjkoOPTEK7BdHxZNwiNdnJ0aWNhmvHkwkaN2w71k
#Karen (user_id: 1)

### Sessions Create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "karen@aol.com",
  "password": "password"
}

### Users Create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Dani",
  "email": "dani@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Users Show
GET http://localhost:3000/users/1
Content-Type: application/json
Authorization: Bearer {{ jwt }}

### Users Update
PATCH http://localhost:3000/users/1
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "image": "https://i.pinimg.com/originals/12/89/69/1289690a3bda60315b5fc8bad1a398f5.jpg"
}

### Users Destroy

DELETE http://localhost:3000/users/15
Content-Type: application/json
Authorization: Bearer {{ jwt }}