@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDYzNDUyMjJ9.Fro50m57pQu_W9QVHyEA_wFBM5zhbIVni7raAnbJb14
#Karen logged in (user 1)

### Membership Create
POST http://localhost:3000/memberships/
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "club_id": 8
}

### Membership Destroy

DELETE http://localhost:3000/memberships/25
Content-Type: application/json
Authorization: Bearer {{ jwt }}