###
#Books Index - Search Titles for Work Ids
GET http://localhost:3000/books
Content-Type: application/json

{
  "title_search": "spider"
}

###
#Books Show - Get data (ISBN) about a specific work if it has a reading guide (books without a reading guide return null). API Endpoint and code in controller also is used to pull basic book info for Clubs serializer.
#Good tests - Search for "sea" and 292302 has reading guide, 178065 does not.

GET http://localhost:3000/books/work_id
Content-Type: application/json

{
  "work_id": "318403"
}

###
#Books Get Discussion Questions of Search Title Chosen

GET http://localhost:3000/books/discussion
Content-Type: application/json

{
  "isbn": "9780141186160"
}

###