@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxNCwiZXhwIjoxNjQ2NTAyNjgzfQ.nZHaJSf67Of29bwkKFcm0e_kskaa_Ui1Pu05I-UsN4k
#Betty (user_id: 14)

### Membership Create
POST http://localhost:3000/memberships/
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "club_id": 8
}

### Membership Destroy

DELETE http://localhost:3000/memberships/36
Content-Type: application/json
Authorization: Bearer {{ jwt }}