@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMSwiZXhwIjoxNjQ2MzQ1Njk5fQ.7sYWgmaPRuXS0YauCVtPGnLCJH8as2icawvBj6lh2cU
#Corrie (user 11)

### Sessions Create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "corrie@gmail.com",
  "password": "password"
}

### Users Create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Test email",
  "email": "test@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Users Show
GET http://localhost:3000/users/11
Content-Type: application/json
Authorization: Bearer {{ jwt }}

### Users Update
PATCH http://localhost:3000/users/13
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "name": "Test Test OKAY!",
  "email": "corrie@gmail.com",
  "image": "https://pbs.twimg.com/profile_images/1009548186086756353/c-heXTFI_400x400.jpg",
  "location": "THE INTERNET",
  "about": "Should not be able to update this",
  "twitter": "@testest"

}

### Users Destroy

DELETE http://localhost:3000/users/12