# User.create!([
#   {name: "Abby Keating", email: "abby@gmail.com", password_digest: "$2a$12$Cak0MCZNJDjgey18.OgLbuXRd5LPUWh3JYC5ofKgJ2Sr9CfBYMYYq", image: "https://pbs.twimg.com/profile_images/1455996520050872328/c86jxMqc_400x400.jpg", location: "Waukesha, WI", about: "I don’t join social media platforms often. But, when I do, it’s worth a read.", twitter: "@abbyreads"},
#   {name: "Lost in a Book", email: "lost@gmail.com", password_digest: "$2a$12$D0/YwVkZsZzyXWerixk7B.LD0JTyoIca57NrumKSHfJ5qWwaVLaIS", image: "https://www.treehugger.com/thmb/wfKpiCka8T8HsLKMN2kXNHm462U=/3798x3798/smart/filters:no_upscale()/pooja-sajan-wp3peZT5U-c-unsplash-5d3877dd1d5f496e87941edd690c25f3.jpg", location: "Madison, WI", about: "Some say they get lost in books, but I find myself, again and again, in the pages of a good book. Humanly speaking, there is no greater teacher, no greater therapist, no greater healer of the soul, than a well-stocked library.", twitter: "@lostinabook"},
#   {name: "Amy Gajkowski", email: "amy@gmail.com", password_digest: "$2a$12$UekGDLTIQiHesDbgFStLvuZu/l5SpvakQrQnlTshYCdt1EXbmXTui", image: "https://urbanmilwaukee.com/wp-content/uploads/2020/12/Amy3-6-768x768.jpg", location: "Milwaukee, WI", about: "The books that help you the most are those which make you think the most.", twitter: "@kazames"},
#   {name: "Lila", email: "lila@gmail.com", password_digest: "$2a$12$9NLbBMebgh8ywD7RkR5os.YXcPqCplVmMUzBvYPT/3dibaDn2hx5q", image: "https://ocep.northwestern.edu/files/img/meet-the-team/lila-pic.jpg", location: "Chicago", about: "Love reading but only on here because Corrie made me", twitter: "@lilargh"},
#   {name: "Gayle Sheer", email: "gayle@gmail.com", password_digest: "$2a$12$ri/eT9yJ8UK0dn9B43fute25miA68Z89y0M73LCEdFN4.Vlx/icuS", image: "https://i.pinimg.com/280x280_RS/e2/5f/e1/e25fe10af7d1e442ed4ab30a32071cce.jpg", location: "Chicago", about: "Coffee. Quilting. Mom of @Boggie the Doggie. And books.", twitter: "@gaylethesnail"},
#   {name: "Corrie", email: "corrie@gmail.com", password_digest: "$2a$12$fkT5aPgnNAF.OuuRklvYteOw3miSxx6GL4LWNZkV0pqkr7oxMjbna", image: "https://pbs.twimg.com/profile_images/1009548186086756353/c-heXTFI_400x400.jpg", location: "Chicago", about: "Former comms professional learning to code so I can use words a little differently. Mother, golfer, feminist, & Packers/Cubs/Northwestern fan. Go Cats!", twitter: "@corrieleech"},
#   {name: "Jacky Jack", email: "jack@gmail.com", password_digest: "$2a$12$CENSEWMPzXjrPQmZJ04VEev00rLIsrPE3HqYIjOeHj647RBdTSjjq", image: "https://media-exp1.licdn.com/dms/image/C4D03AQEdFJfr0YB28Q/profile-displayphoto-shrink_800_800/0/1631924012127?e=1653523200&v=beta&t=eVjmyfxoOiSW8eTdJ8qByDP8dE7ePPoiZ5VzWUyLDsQ", location: "Chicago, IL", about: "Dev that reads!", twitter: "@jackthejack"},
#   {name: "Eric Lee", email: "eric@gmail.com", password_digest: "$2a$12$3vCQS.PDRJnoRsCh6OAdFOKeh6A8DkQFrpicPByd0pwqdbpALwK1m", image: "https://media-exp1.licdn.com/dms/image/C4E03AQGz4_pirPyBKQ/profile-displayphoto-shrink_200_200/0/1627659165738?e=2147483647&v=beta&t=B4HRNkQzDmhdNWNHxctWromJxR9G7aVE0SHY72uiJWw", location: "Logan Square", about: "Insane ability to deep focus on read on a Kindle when toddlers are screaming.", twitter: "@bronzedpanda"},
#   {name: "Karen Johnson", email: "karen@aol.com", password_digest: "$2a$12$VLUT7selPE4MnnhxZjVvluwFtkMI7KbbTQju7F1wQFd48GT.CCAiK", image: "https://pbs.twimg.com/profile_images/1224095594425221125/Y_ieN4ba_400x400.jpg", location: "Columbus, OH", about: "46 years young. Soccer mom of three. Live, laugh, love... wine!", twitter: "@karenestkaren"},
#   {name: "Sara Stewart", email: "sara@gmail.com", password_digest: "$2a$12$zMwKpmCdlB6qtytGB4SNsOYpIejxpRPSzZF0TKEy2KCxMm5i0qK0q", image: "https://www.healthymatsu.org/wp-content/uploads/Sarah-Deardorff-Sq.-400-x-400-px.png", location: "Milwaukee", about: "Fitness freak: I burn calories by jumping to conclusions.", twitter: "@cartwheels"},
#   {name: "Kristin Bissell", email: "kristin@gmail.com", password_digest: "$2a$12$X/qZlHYghs/OoETjszalAupSPghqxZIabIPS/dIkHHMb2QZA7f8je", image: "https://2019.images.forbesjapan.media/authors/764/photos/400x400/ec126321ba237a8544e64f7b7d6b3e93.jpg", location: "Waukesha, WI", about: "Be a flamingo in a flock of pigeons.", twitter: "@kristinbissell"},
#   {name: "Heather Aplin", email: "heather@gmail.com", password_digest: "$2a$12$V54JtEEXUFGnFovR8oa.4es4z85A1VWaaCN7QtGdSq5GU.1jh9eci", image: "https://pbs.twimg.com/profile_images/1383913827377373187/MzxvosxP_400x400.jpg", location: "Madison, WI", about: "A woman of mystery and power, whose power is exceeded only by her mystery", twitter: "@readwise"},
#   {name: "Erin Jacksone", email: "erin@gmail.com", password_digest: "$2a$12$B19WG.2QZoSQHpTpj78w7.68O2TXUlqFcz3vhm1iEKY1n18fUX29e", image: "https://media-exp1.licdn.com/dms/image/D5635AQG8X7_WQTgNqw/profile-framedphoto-shrink_800_800/0/1638753065571?e=1648141200&v=beta&t=X_oSTxd_drE8NHsczlQYocgrLBf7OP2kPykIUMfyHVE", location: "Portland, OR", about: "Full stack dev, runner, reader.", twitter: "@erinesterin"},
#   {name: "Betty Friedan", email: "betty@gmail.com", password_digest: "$2a$12$tRtNDtV2/324t/vbkC/r5.rN9vBFCgtyNtZUCECx5TpHOyDrm9Lhi", image: "https://www.biography.com/.image/t_share/MTE5NDg0MDU0OTcyNDMzOTM1/betty-friedan-wc-9302633-1-402.jpg", location: "NYC", about: "Journalist, activist, and co-founder of the National Organization for Women", twitter: "@problemthathasnoname"},
#   {name: "Christina Donley", email: "christina@gmail.com", password_digest: "$2a$12$yAGPNKn.PrDTmq9XZajVqeQ52Qr.ymtGH41707XJYDyZ2UHIMv/Ne", image: "https://media-exp1.licdn.com/dms/image/C4D03AQHM055OFIKJcg/profile-displayphoto-shrink_800_800/0/1568062379127?e=1653523200&v=beta&t=fv9CXMvcPZwcTgi0g4wgFFtoqJSQ4eQrHrCbZDhkwnY", location: "Chicago", about: "When I'm not lifting heavy things, I'm reading.", twitter: "@stinasusan"},
#   {name: "Yuna", email: "yuna@gmail.com", password_digest: "$2a$12$9RxQ35Cp2wFlgeghocpgT.NP8neN8C2SRgNU7UkuxlDAXpTaAaJku", image: "https://scontent-ort2-1.xx.fbcdn.net/v/t1.6435-9/36223447_10103009385853445_3624771137319206912_n.jpg?_nc_cat=101&ccb=1-5&_nc_sid=174925&_nc_ohc=QWTC9TDDNhoAX-vaczD&_nc_ht=scontent-ort2-1.xx&oh=00_AT9_HqyUG-uIBuVqA7B_XzfgU7mWcVr4ThPwxSYU__X5Uw&oe=6260F6B9", location: "Chicago", about: "Book lover. Currently obsessed with princesses, Disney stories and dry erase markers.", twitter: "@yunaestyuna"}
# ])

# Club.create!([
#   {name: "LadyBros", work_id: 653196, isbn: "9780593230251", is_active: false},
#   {name: "Feminist Book Club", work_id: nil, isbn: "9780385490443", is_active: true},
#   {name: "Classics", work_id: nil, isbn: "9780385474542", is_active: true},
#   {name: "Tiger Moms", work_id: nil, isbn: "9780385343848", is_active: false},
#   {name: "Jack's Club", work_id: nil, isbn: "9780525656975", is_active: true},
#   {name: "Jack's Second Club", work_id: nil, isbn: "9780812979893", is_active: true},
#   {name: "Riding the Second Wave", work_id: 137, isbn: "9780812975994", is_active: true},
#   {name: "Crazy Readers United", work_id: 40773, isbn: "9780307387387", is_active: true},
#   {name: "Karen's Book Klub", work_id: 40773, isbn: "9780307387387", is_active: false},
#   {name: "Digital Get Down", work_id: 586568, isbn: "9780525560586", is_active: true},
#   {name: "ChiTown Readers", work_id: nil, isbn: "9780812975406", is_active: true},
#   {name: "Water Readers: Books About Water", work_id: 292302, isbn: "9780141186160", is_active: true},
#   {name: "Mad Monsters", work_id: nil, isbn: "9780593199213", is_active: false},
#   {name: "All in the Family", work_id: 31572, isbn: "9780385411721", is_active: true},
#   {name: "To Kingdom Come", work_id: nil, isbn: "9780553805413", is_active: true},
#   {name: "East V West", work_id: nil, isbn: "9780142004234", is_active: true},
#   {name: "Who Run The World?", work_id: nil, isbn: "9780767930512", is_active: true},
#   {name: "Monsters", work_id: nil, isbn: "9781594633607", is_active: false},
#   {name: "Tiger", work_id: nil, isbn: "9781594633607", is_active: false},
#   {name: "Monsters!", work_id: nil, isbn: "9781594633607", is_active: false},
#   {name: "LadyBros 2.0", work_id: 50048, isbn: "9780375759642", is_active: true},
#   {name: "Froggies!", work_id: nil, isbn: "9780698182660", is_active: false},
#   {name: "Animal Lovers", work_id: nil, isbn: "9780698182660", is_active: false},
#   {name: "Animal Lovers", work_id: nil, isbn: "9780698182660", is_active: true},
#   {name: "Ugly Bettys", work_id: nil, isbn: "9780525559351", is_active: true},
#   {name: "Tiger Moms 2.0", work_id: nil, isbn: "9780385343848", is_active: true},
#   {name: "Page Turners", work_id: 326569, isbn: "9780451524935", is_active: true},
#   {name: "More Than Words", work_id: 550168, isbn: "9780399590504", is_active: true}
#   ])

# Membership.create!([
#   {club_id: 1, user_id: 1},
#   {club_id: 1, user_id: 4},
#   {club_id: 1, user_id: 8},
#   {club_id: 1, user_id: 3},
#   {club_id: 17, user_id: 11},
#   {club_id: 2, user_id: 4},
#   {club_id: 2, user_id: 8},
#   {club_id: 2, user_id: 2},
#   {club_id: 3, user_id: 2},
#   {club_id: 3, user_id: 3},
#   {club_id: 3, user_id: 9},
#   {club_id: 3, user_id: 10},
#   {club_id: 4, user_id: 5},
#   {club_id: 4, user_id: 6},
#   {club_id: 4, user_id: 7},
#   {club_id: 4, user_id: 9},
#   {club_id: 5, user_id: 5},
#   {club_id: 5, user_id: 6},
#   {club_id: 5, user_id: 7},
#   {club_id: 5, user_id: 10},
#   {club_id: 7, user_id: 13},
#   {club_id: 8, user_id: 1},
#   {club_id: 10, user_id: 11},
#   {club_id: 11, user_id: 11},
#   {club_id: 12, user_id: 11},
#   {club_id: 13, user_id: 11},
#   {club_id: 15, user_id: 11},
#   {club_id: 17, user_id: 14},
#   {club_id: 5, user_id: 14},
#   {club_id: 3, user_id: 11},
#   {club_id: 18, user_id: 6},
#   {club_id: 17, user_id: 6},
#   {club_id: 19, user_id: 6},
#   {club_id: 20, user_id: 6},
#   {club_id: 21, user_id: 6},
#   {club_id: 22, user_id: 6},
#   {club_id: 23, user_id: 14},
#   {club_id: 4, user_id: 14},
#   {club_id: 24, user_id: 14},
#   {club_id: 25, user_id: 14},
#   {club_id: 26, user_id: 14},
#   {club_id: 27, user_id: 14},
#   {club_id: 28, user_id: 6},
#   {club_id: 29, user_id: 1},
#   {club_id: 30, user_id: 1},
#   {club_id: 31, user_id: 6},
#   {club_id: 3, user_id: 1},
#   {club_id: 35, user_id: 24},
#   {club_id: 3, user_id: 24},
#   {club_id: 16, user_id: 1},
#   {club_id: 36, user_id: 6},
#   {club_id: 2, user_id: 1},
#   {club_id: 35, user_id: 6},
#   {club_id: 3, user_id: 6},
#   {club_id: 17, user_id: 4},
#   {club_id: 35, user_id: 4},
#   {club_id: 33, user_id: 4},
#   {club_id: 36, user_id: 4},
#   {club_id: 37, user_id: 4},
#   {club_id: 16, user_id: 25},
#   {club_id: 16, user_id: 6},
#   {club_id: 1, user_id: 5},
#   {club_id: 34, user_id: 7},
#   {club_id: 34, user_id: 24},
#   {club_id: 34, user_id: 1},
#   {club_id: 34, user_id: 6},
#   {club_id: 38, user_id: 11},
#   {club_id: 14, user_id: 11},
#   {club_id: 34, user_id: 11},
#   {club_id: 39, user_id: 11},
#   {club_id: 40, user_id: 11},
#   {club_id: 2, user_id: 11},
#   {club_id: 42, user_id: 11},
#   {club_id: 41, user_id: 11},
#   {club_id: 43, user_id: 11},
#   {club_id: 1, user_id: 11},
#   {club_id: 8, user_id: 4},
#   {club_id: 44, user_id: 11},
#   {club_id: 8, user_id: 11},
#   {club_id: 35, user_id: 11},
#   {club_id: 36, user_id: 11},
#   {club_id: 6, user_id: 11},
#   {club_id: 3, user_id: 23},
#   {club_id: 35, user_id: 5},
#   {club_id: 23, user_id: 5},
#   {club_id: 31, user_id: 5},
#   {club_id: 33, user_id: 11},
#   {club_id: 37, user_id: 11}
# ])

Message.create!([
  {club_id: 1, user_id: 1, body: "Question 1: Many of Tara's father's choices have an obvious impact on Tara's life, but how did her mother's choices influence her? Tara's mom is complicit!!! HOW CAN YOU DO THAT TO A CHILD??!?!?!?!", category: "formal"},
  {club_id: 1, user_id: 8, body: "Question 2: Tara's brother Tyler tells her to take the ACT. What motivates Tara to follow his advice? Oh really? I totally thought it was the second thing, because that's when she...", category: "formal"},
  {club_id: 1, user_id: 1, body: "Wow, Tara's story is so inspring!!! OMG!", category: "informal"},
  {club_id: 1, user_id: 3, body: "Karen, you would think that. I found it incredibly scary a family like that could exist... and more probably do.", category: "informal"},
  {club_id: 2, user_id: 1, body: "I didn't think War is Peace was a contradiction. There is no contradiction on a grand scale...", category: "formal"},
  {club_id: 2, user_id: 8, body: "What would you do to undermine The Party? Knowing what you know now, how would you extricate yourself from the fate that awaits you? I would... ", category: "formal"},
  {club_id: 2, user_id: 2, body: "Can we talk about how much this is like today????", category: "informal"},
  {club_id: 3, user_id: 2, body: "Question 1: Idra Novey chose to set most of her novel in an unnamed place. Why? I loved this choice; I found myself flirting in and out of historical fact and questioning my stereocategorys of various islands.", category: "formal"},
  {club_id: 3, user_id: 3, body: "Question 1: Idra Novey chose to set most of her novel in an unnamed place. Why? UGH I HATED THIS. Like, just say it was Cuba. It was so obvious that's what she was trying to do...", category: "formal"},
  {club_id: 3, user_id: 9, body: "Did you guys also question what your silence is costing us?", category: "informal"},
  {club_id: 3, user_id: 10, body: "Question 2: Those Who Knew begins with Lena but quickly introduces several other characters points of view, creating a mosaic of narrative voices. How did that choice keep the plot moving? I loved how she wrote this. It was like each new character advanced the plot the tinest bit, and added new information that felt like the urgency of the mystery was ramping up. SPOILER ALERT: The ending is...", category: "formal"},
  {club_id: 3, user_id: 10, body: "Wow, I thought she really spoke with uncommon prescience to the swirl that is all around us", category: "informal"},
  {club_id: 4, user_id: 5, body: "I thought Wilkerson points us forward to ways America can move beyond the artificial and destructive separations of human divisions, toward hope in our common humanity.", category: "formal"},
  {club_id: 4, user_id: 6, body: "By linking the caste systems of America, India, and Nazi Germany, Wilkerson explores eight pillars that underlie caste systems across civilizations, including divine will, bloodlines, stigma, and more.", category: "formal"},
  {club_id: 4, user_id: 7, body: "After reading about the surprising health costs of caste, in depression and life expectancy, and the effects of this hierarchy on our culture and politics, I cannot help but wonder what a world we would live in without a caste.", category: "formal"},
  {club_id: 4, user_id: 9, body: "This was eye-opening. I loved how it blended people and history, and reexaminationed what lies under the surface of our ordinary lives and of American life today. In my life, I can think of...", category: "formal"},
  {club_id: 4, user_id: 5, body: "And we thought America wasn't racist because we elected Obama... eye roll.", category: "informal"},
  {club_id: 5, user_id: 5, body: "Question 1: In her introduction, Susan Orlean says that, like everything else Fitzgerald wrote, This Side of Paradise is a treatise about class. I agree..", category: "formal"},
  {club_id: 5, user_id: 6, body: "Question 3: Are the romantic pursuits of Amory and his friends primarily satisfying or disillusioning? How does money, or the lack of it, play a part in the pursuit of love? I thought they were disillusioning. There is no way without money any of these relationships survive...", category: "formal"},
  {club_id: 5, user_id: 7, body: "Question 7: Is This Side of Paradise in any way a tragic novel? How does it attempt to explain tragedy or loss? Do you think Fitzgerald intended a mournful or ultimately hopeful perspective? Why or why not? I'm laughing all the way to the bank as I write this. How can this not be a tragic novel? Isn't that why we read it...", category: "formal"},
  {club_id: 5, user_id: 8, body: "Oh Lila, you be cray.", category: "informal"},
  {club_id: 5, user_id: 6, body: "Can you even imagine if Leo played Amory??? Haaa ha ha ha ha.", category: "informal"},
  {club_id: 16, user_id: 25, body: "<p>How am I the first one here when my mom and dad are already on this site? Sigh... </p>", category: "informal"},
  {club_id: 2, user_id: 1, body: "Trump was the greatest.", category: "informal"},
  {club_id: 2, user_id: 4, body: "<p>Wow, and we barely survived the Trump years.</p>", category: "informal"},
  {club_id: 16, user_id: 25, body: "<p>1. <strong>How does the use of an unorthodox narrator--\"this dead-but-not-gone thing\" [p. 37]--contribute to the emotional impact of the story as it unfolds? </strong></p><p>I loved this choice. I thought it made the family scenes more real... it reflects the emotional weight we continue to carry after loved ones die so that we can remember them as part of our families forever. </p>", category: "formal"},
  {club_id: 17, user_id: 14, body: "This is a message from beyond the grave **scary music plays**", category: "informal"},
  {club_id: 19, user_id: 6, body: "I love John Steinbeck!!!!", category: "informal"},
  {club_id: 19, user_id: 6, body: "Question 2: This is a quintessentially American book because of the way that Steinbeck uses...", category: "informal"},
  {club_id: 2, user_id: 4, body: "<p>Contradiction plays a huge role within the framework of Doublethink... don't you think?</p>", category: "formal"},
  {club_id: 8, user_id: 4, body: "<p>Karen, what did you think of this book? </p><ul><li>I thought of you when the cat died.</li><li>Then I thought you'd hate it when the cat came back to life.</li><li>But I <em>really </em>hated it when the cat died again!</li></ul>", category: "informal"},
  {club_id: 8, user_id: 4, body: "<p>#14 - has to be why Didion didnt... </p>", category: "formal"},
  {club_id: 16, user_id: 6, body: "<p>You're way more advanced, Yuna. Love, Emo Christina.</p>", category: "informal"},
  {club_id: 16, user_id: 6, body: "<p>Couldn't agree more, Yuna. I also thought it added a sense of continuity to the narrative. Like, loved how we got multiple voices in each scene based on who was talking. </p>", category: "formal"},
  {club_id: 33, user_id: 11, body: "Number 9: My cat.", category: "formal"},
  {club_id: 33, user_id: 22, body: "This is an informal message", category: "informal"},
  {club_id: 33, user_id: 22, body: "This is a formal message :o)", category: "formal"},
  {club_id: 34, user_id: 11, body: "Was anyone weirded out by this book?", category: "informal"},
  {club_id: 3, user_id: 6, body: "<p>Agree with Abby. Either set the book in Cuba or don't. Feels lazy to invoke stereotypes without having to do a deep dive on the history. Like, she wanted to write a historical fiction novel but didn't want to <strong><em>go there</em></strong> go there.</p>", category: "formal"},
  {club_id: 3, user_id: 1, body: "<p>Reading this on the beach in Playa del Carmen at an all-inclusive with a frozen daiquiri in hand was so perfect! </p>", category: "informal"},
  {club_id: 1, user_id: 1, body: "<p><strong>Re question 2: </strong>Her brother is a jerk! I would have ran away at this point.</p>", category: "formal"},
  {club_id: 34, user_id: 11, body: "<p><strong>5. Is Charlie a likable character? Can you understand Alice’s attraction to him?</strong></p><p>No and no. Now that I'm removed from reading the book a bit, all I can remember is the gross \"privileged good 'ol boy\" culture when he was with his family and then the flip to being a sober Christian president based on one of the worst presidents ever, and I just can't go there. Also, I think that kind of charisma might be hard to have come through in just words.</p>", category: "formal"},
  {club_id: 34, user_id: 7, body: "<p>Ha ha ha. I was too! Like, it was supposed to be a mash up of current-ish first ladies but I could only see Laura/\"W\"? Also, we're supposed to believe that Laura Bush is secretly a liberal atheist? Right. </p>", category: "informal"},
  {club_id: 34, user_id: 11, body: "<p>Wait wait wait. This <a href=\"https://www.theatlantic.com/entertainment/archive/2010/05/the-secret-inner-life-of-laura-bush/56644/\" target=\"_blank\">Atlantic article from 2010</a>. How did I miss this? </p>", category: "informal"},
  {club_id: 35, user_id: 11, body: "<p>This is a test</p>", category: "formal"},
  {club_id: 3, user_id: 23, body: "<p>Oh great. It sometimes loads, and sometimes doesn't, Corrie.</p>", category: "formal"},
  {club_id: 37, user_id: 11, body: "<p>#first</p>", category: "informal"},
  {club_id: 5, user_id: 6, body: "<p>Lila, to question 7. </p><ul><li>I think you're right that this is obviously a tragic novel.</li><li>But then again, I can't help but think that it isn't.</li></ul>", category: "formal"},
  {club_id: 5, user_id: 6, body: "<p>Pandemic quote anyone? \"Here's to alcohol, the rose colored glasses of life.\"</p>", category: "informal"},
  {club_id: 35, user_id: 6, body: "<p><strong>Re: Question 1 - </strong>I found that the physical things Atwood described as organic, raw terms were rooted in the present, while the ephemeral images were in the past. So, when you think of it, the past is a collection of dreams and memories, while the current day reality is harsh, real and fact-based, which I think were themes of the novel.</p>", category: "formal"},
  {club_id: 1, user_id: 4, body: "<p><strong>Question 2: Tara's brother Tyler tells her to take the ACT. What motivates Tara to follow his advice?</strong></p><p>I thought the seeds of her motivation were planted when the first thing happened, but really what forced her decision was the second thing.</p>", category: "formal"},
  {club_id: 36, user_id: 6, body: "<p>#first!</p>", category: "informal"},
  {club_id: 35, user_id: 5, body: "<p>I think you're right Christina. I had the same feeling too, although I coudln't help but think Atwood was trying to make a connection to the lack of joy and pleasure we can sometimes feel in the present, even when things are going okay.</p>", category: "formal"},
  {club_id: 1, user_id: 4, body: "<p>Ha ha Abby, really? There was love in the family... </p>", category: "informal"},
  {club_id: 35, user_id: 5, body: "<p>“If we were all on trial for our thoughts, we would all be hanged.”</p><p>It's like Atwood was staring into my soul.</p>", category: "informal"},
  {club_id: 35, user_id: 11, body: "<p>I did think of you when I read that, Gayle. Ha ha ha ha.</p>", category: "informal"},
  {club_id: 35, user_id: 24, body: "<p><strong>5. Atwood offers a vision of the dual nature of people, houses, appearances, and more. How does she make use of darkness and light, and to what purpose?</strong></p><p>I think this is a fascinating question. I think the darkest moments were actually the ones I enjoyed the most, but see where Atwood was going with this.</p>", category: "formal"},
  {club_id: 35, user_id: 24, body: "<p>Not me. I'd be safe. </p>", category: "informal"},
  {club_id: 35, user_id: 6, body: "<p>Lies.</p>", category: "informal"},
  {club_id: 3, user_id: 6, body: "<p>Deep, Kristin. Is that the wine talking?</p>", category: "informal"},
  {club_id: 3, user_id: 11, body: "<p>Ouch, Stina. Play nice.</p>", category: "informal"},
  {club_id: 34, user_id: 1, body: "<p>Did anyone else not finish this book?</p>", category: "informal"},
  {club_id: 34, user_id: 1, body: "<p><strong>2. Alice’s grandmother passes down her love of reading. How else is Alice influenced by her grandmother?</strong></p><p>Strangely, I don't think her grandmother was the best influence. Her grandmother taught her that you can be who you are, but not have to stand up for what you believe in and voice those beliefs in public.</p>", category: "formal"},
  {club_id: 34, user_id: 6, body: "<p>I disagree, Karen. Re: question 2, I think her grandmother encouraged her to be a free spirit and also to follow love regardless of the circumstances. Her relationship with the doctor and Alice's relationship with Charlie are so similar - loving the person they love brings consequences in their lives, for better or worse.</p>", category: "formal"},
  {club_id: 34, user_id: 24, body: "<p><strong>3. Why does Andrew remain such an important figure to Alice, even decades later? Do you think they would have ended up together under different circumstances?</strong></p><ul><li>It's the idea of love that keeps him an important figure, and really, I find it sad that she carries a \"grass is always greener\" attitude in her heart. What a sad way to live your life.</li><li><em>No way </em>they'd be together. High school romances rarely survive even 6 months.</li></ul>", category: "formal"},
  {club_id: 34, user_id: 24, body: "<p>It was a struggle, but I did.</p>", category: "informal"}
])

  